name: calorie_lens_ai_app
description: "Calorie Lens AI - Your Personal Nutrition Assistant"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # ğŸ—ï¸ State Management & Architecture  
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  provider: ^6.1.5+1

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2


   # ğŸ”§ Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.3.2

  # ğŸŒ Network & Data
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  
  # ğŸ’¾ Local Storage
  shared_preferences: ^2.2.2

  # Utils
  connectivity_plus: ^7.0.0
  internet_connection_checker: ^3.0.1

  # Environment
  flutter_dotenv: ^6.0.0

  # File Path Manipulation
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Testing and Code Generation
  mockito: ^5.5.1
  bloc_test: ^10.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  retrofit_generator: ^9.2.0
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
